# Generated by Django 6.1 on 2026-08-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArenaBook', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='sport_category',
            options={'verbose_name': 'Sport_Category', 'verbose_name_plural': 'Sport_Categories'},
        ),
    ]
