# Generated by Django 6.1 on 2026-08-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArenaBook', '0004_alter_city_options_alter_contact_us_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='sport_category',
            name='sport_image',
            field=models.ImageField(blank=True, null=True, upload_to='sport_categories'),
        ),
        migrations.AddField(
            model_name='turf',
            name='turf_images',
            field=models.ImageField(blank=True, null=True, upload_to='turfs'),
        ),
        migrations.CreateModel(
            name='Turf_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='turf_images')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArenaBook.turf')),
            ],
        ),
    ]
