# Generated by Django 6.1 on 2026-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArenaBook', '0005_rename_image_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='email_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=100),
        ),
    ]
